# Site settings
title: "Public interest Tech blog template"
title-font-size: '4em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

email: pit@newamerica.com
description: > 
  A blog template for those in the Public Interest Tech program
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://newamericaPIT.github.io/pit-blog-template"

permalink: :url/

# Build settings
markdown: kramdown
highlight: rouge
paginate: 20
paginate_path: /page:num/


# Tracker
analytics:

#CSS
sass:
  style: compressed


include: [_pages]

plugins: [jekyll-paginate, jekyll-seo-tag]